### ISSUE TITLE
Setup Informal Hosted Cache

### ISSUE THREAD

**Issue by JonathanLorimer** [informalsystems/cosmos.nix#155]
I would like to setup a nix cache hosted by informal, probably using digital ocean spaces, and cloudflare as a cdn. Spaces is relatively cheap https://www.digitalocean.com/products/spaces, and so is cloudflare.

I think our cache size is too big for Cachix's free tier, which is evicting entries that we still need!

This is leading to CI times longer than an hour, which is unacceptable IMO.
```[tasklist]
### Tasks
- [ ] Choose an S3 compatible storage (right now leaning towards digital ocean spaces
- [ ] Choose a dns provider
- [ ] Ideally use terraform to provision the infrastructure
```

**Comment by dzmitry-lahoda** [comment]
ComposableFi has sub to cachix. We have > 100GB caches. Afaik it is 1TB. I can create some NAME cached and share token in cachix.   I guess as long as ComposableFi will exists and use nix it will be alive.

**Comment by dzmitry-lahoda** [comment]
Also can check i can move this repo to nix-community so they use their cache (again - i guess a lot will be shared)

**Comment by JonathanLorimer** [comment]
Moving to `nix-community` is an interesting idea. I know informal depends on this repo for CI, so not sure how they would feel about moving the repo.

**Comment by dzmitry-lahoda** [comment]
nix-community has `ethereum.nix` , but sure - cosmos is smaller.

**Comment by JonathanLorimer** [comment]
> nix-community has `ethereum.nix` , but sure - cosmos is smaller.

I didn't mean to suggest it was a bad idea. I am for it. I just meant that, since informal depends on this repo very heavily for CI, they might not want to give up control of it.

**Comment by dzmitry-lahoda** [comment]
> Moving to nix-community is an interesting idea. I know informal depends on this repo for CI, so not sure how they would feel about moving the repo.

may be moved to cosmos, at least ask. may be.
