### ISSUE TITLE
Repo cleanup and refactor

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/cosmos.nix#174]
so can add it and grab binaries from pkgs, instead direct reference input
```[tasklist]
### Tasks
- [x] Refactor to use flake-parts
- [x] Add overlay
- [x] Remove pre-commit hooks
- [x] Expose a library for common cosmos operations
```

**Comment by JonathanLorimer** [comment]
This is a great idea. I also want to refactor this to use https://flake.parts/, and get away from flake-utils. As well as get rid of pre-commit hooks as mentioned here https://github.com/informalsystems/cosmos.nix/issues/156

**Comment by JonathanLorimer** [comment]
I hope you don't mind that I renamed the issue so it can encompass some larger goals

**Comment by dzmitry-lahoda** [comment]
also 

https://github.com/Platonic-Systems/process-compose-flake/blob/ea1607cead57ce72dd06e178b4d55884a3be8854/example/flake.nix#L6

it allows to override `systems` supported.  

https://github.com/nix-systems/nix-systems
